In [ ]:
import numpy as np

In [ ]:
l1 = [1,2,3,4]

print(l1)

[1, 2, 3, 4]


In [ ]:
arr1 = np.array([1,2,3,4,5,6])

print(arr1)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
my_arr = np.array([[1,2],
                   [3,4],
                   [5,6],
                   [7,8]])


In [ ]:
my_arr[1,1]

np.int64(4)

In [ ]:
arr_dataType = np.array([1,2,3,4,5],dtype=np.int32)
print(arr_dataType)

[1 2 3 4 5]


In [ ]:
my_arr.shape

(4, 2)

In [ ]:
my_arr.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
print(my_arr)
my_arr.min(axis=0)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([1, 2])

In [ ]:
my_arr.dtype

dtype('int64')

In [ ]:
zeros = np.zeros((3,3))
zeros.dtype

dtype('float64')

In [ ]:
rng = np.arange(10)

In [ ]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
l_space = np.linspace(1,20,5)
l_space

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
emp_like = np.empty_like(l_space)
emp_like

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
ide = np.identity(2)
ide

array([[1., 0.],
       [0., 1.]])

In [ ]:
arr = np.arange(99)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
print(arr.reshape(3,33))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [ ]:
x = [[1,2,3],[4,5,6],[7,8,9]]
print(x)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
arr_check = np.array(x)

In [ ]:
arr_check

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_sum = arr_check.sum(axis=0)

In [ ]:
arr_sum

array([12, 15, 18])

In [ ]:
print(arr_check.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
arr_sum.size

3

In [ ]:
arr_check.size

9

In [ ]:
one = np.array([1,2,456,3,2])

one.argmax()

np.int64(2)

In [ ]:
one.argmin()

np.int64(0)

In [ ]:
one.argsort()   # give the indexes of given array in which the array becomes sorted

array([0, 1, 4, 3, 2])

In [ ]:
one.ravel()

array([  1,   2, 456,   3,   2])