## Numpy Basics

In [3]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
print(array)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Creating Array from scratch

In [6]:
zeros = np.zeros((3, 3))
print(zeros)

ones = np.ones((2, 4))
print(ones)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
full = np.full((2, 2), 7)
print(full)


[[7 7]
 [7 7]]


In [10]:
random = np.random.rand(3, 3)
print(random)

[[0.28424235 0.93817047 0.17589184]
 [0.64391586 0.9829431  0.29551192]
 [0.93583525 0.03656291 0.92761564]]


In [11]:
sequence = np.arange(0, 10, 2)
print(sequence)


[0 2 4 6 8]


### Vector, Matices and tensor

In [14]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [26]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print("Shape: ", arr.shape)

print("Size: ", arr.size)

print("Data type: ", arr.dtype)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

added = arr1 + arr2
print("Added arrays: ", added)

multiplied = arr1 * arr2
print("Multiplied arrays: ", multiplied)

dot_product = np.dot(arr1, arr2)
print("Dot product: ", dot_product)

mean = np.mean(arr)
print("Mean: ", mean)

std_dev = np.std(arr)
print("Standard Deviation: ", std_dev)


Shape:  (2, 3)
Size:  6
Data type:  int64
Added arrays:  [5 7 9]
Multiplied arrays:  [ 4 10 18]
Dot product:  32
Mean:  3.5
Standard Deviation:  1.707825127659933


In [27]:
arr = np.array([1, 2, 3, 4, 5])
print("Shape: ", arr.shape)

Shape:  (5,)


In [31]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

reshaped = arr.reshape((3,3))

print("Reshaped array: \n", reshaped)

Reshaped array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
arr = np.arange(1, 12)

print("Original array: ", arr)

reshaped = arr.reshape((11, 1))
print("Reshaped array: \n", reshaped)

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
